version: '3'

services:
  app:
    tty: true
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: ./dockerfile
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    ports:
      - '5000:5000'
    links:
      - 'mysql:mysqldb'
      - 'redis:redisdb'
    depends_on:
      - mysql
      - redis

  mysql:
    restart: always
    container_name: db
    # platform: linux/amd64
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'

  redis:
    restart: always
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    restart: always
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS= ${REDIS_HOST}:redis:6379
    ports:
      - '8081:8081'
