version: '3'

services:
  app:
    tty: true
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: ./dockerfile
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    ports:
      - '5000:5000'
    links:
      - 'mysql:mysqldb'
    depends_on:
      - mysql

  mysql:
    restart: always
    container_name: db
    # platform: linux/amd64
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
